version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "feat"
      include: "scope"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    security-updates: true
    open-pull-requests-limit: 10
    target-branch: "main"
    severities:
      - "high"
      - "critical"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "feat"
      include: "scope"
