run:
  timeout: 5m
  go: "1.22"

linters-settings:
  gocritic:
    enabled-tags:
      - performance
  lll:
    line-length: 200

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - forcetypeassert
    - gocritic
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - revive # replacement for golint
    - staticcheck
    - typecheck
    - unused
    - whitespace
