name: test code
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  golang:
    strategy:
      matrix:
        go-version: [1.21.x]
        # temp disable windows tests see https://github.com/docker/image-signer-verifier/pull/154
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git to use LF
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
      - name: go test
        run: go test -v ./... -coverprofile=coverage.out -covermode=atomic -coverpkg=./...
      - name: html coverage
        run: go tool cover -html=coverage.out -o coverage.html
